#!/usr/bin/env python3
"""Show the new dynamic button controls"""

print("🎮 GT7 Stream Deck - Dynamic Button Controls")
print()
print("Stream Deck Layout:")
print("[1] [2] [3]")
print("[4] [5] [6]")
print()
print("Button Functions:")
print("🔆 Button 1: Brightness +10% (1-100%)")
print("🔄 Button 2: Cycle screens (Main → Sequential → H-Pattern)")
print("↻  Button 3: Rotate display 90° clockwise") 
print("🔅 Button 4: Brightness -10% (1-100%)")
print("🔄 Button 5: Cycle screens (alternative)")
print("↺  Button 6: Rotate display 90° counter-clockwise")
print()
print("🎛️ Three Screen Options:")
print("1. Main Telemetry - [SHIFT][GT7][GEAR] / [SPEED][RPM][STATUS]")
print("2. Sequential Gears - [G1][G2][G3] / [G4][G5][G6] (paddle shifters)")
print("3. H-Pattern Shifter - [G1][G3][G5] / [G2][G4][G6] (manual transmission)")
print()
print("🔄 Rotation Options: 0°, 90°, 180°, 270°")
print("🔆 Brightness Range: 1-100%")
print()
print("Perfect for dynamic adjustments during racing! 🏁")
